# Generated by Django 4.2.7 on 2023-12-08 03:38

import account.enums
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='email_status',
            field=enumfields.fields.EnumField(default='DIS', enum=account.enums.AccountEmailStatus, max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
