# Generated by Django 4.2.7 on 2023-12-08 07:31

import account.enums
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_is_email_verified_user_email_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitytoken',
            name='event',
            field=enumfields.fields.EnumField(default='NON', enum=account.enums.SecurityTokenEventType, max_length=3),
        ),
    ]
