version: '3'

services:

  redis:
    image: "redis:latest"
    expose:
      - '6379'
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A get_buff worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
    restart: always

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A get_buff beat -l info 
    volumes:
      - .:/code
    depends_on:
      - redis
    restart: always
    
  flower:
    image: mher/flower
    container_name: flower
    command: celery --broker=${REDIS_BROKER_URL} flower --port=5555
    ports:
    - "5555:5555" # docker will expose this ports
    volumes:
      - .:/code/flower
    depends_on:
      - redis
    restart: always
