# Generated by Django 4.2.7 on 2023-12-07 16:15

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import muscle.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', enumfields.fields.EnumField(default='NON', enum=muscle.enums.MuscleGroup, max_length=3)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('front_image_url', models.URLField()),
                ('back_image_url', models.URLField()),
                ('muscle_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='muscle.musclecategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
