# Generated by Django 4.2.7 on 2023-11-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musclecategory',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
