# Generated by Django 4.2.7 on 2023-12-02 15:33

from django.db import migrations
import enumfields.fields
import muscle.enums


class Migration(migrations.Migration):

    dependencies = [
        ('muscle', '0002_musclecategory_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musclecategory',
            name='name',
            field=enumfields.fields.EnumField(enum=muscle.enums.MuscleGroup, max_length=3),
        ),
    ]
