# Generated by Django 4.2.7 on 2023-11-24 13:57

from django.db import migrations, models
import enumfields.fields
import user.enums


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='target_weight_in_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight_target_status',
            field=enumfields.fields.EnumField(default='MAN', enum=user.enums.TargetStatus, max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height_in_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight_in_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(check=models.Q(('weight_in_kg__gt', 0.0), ('weight_in_kg__lt', 500.0)), name='target_weight_in_kg_range_check'),
        ),
    ]
