# Generated by Django 4.2.7 on 2023-12-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='height_in_cm_range_check',
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(check=models.Q(('height_in_cm__gt', 50), ('height_in_cm__lte', 350)), name='height_in_cm_range_check'),
        ),
    ]
