# Generated by Django 4.2.7 on 2023-12-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userprofile_height_in_cm_range_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='height_in_cm',
            field=models.IntegerField(blank=True, default=170, null=True),
        ),
    ]
