# Generated by Django 4.2.7 on 2023-11-27 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_remove_customtrainingset_min_count_and_more'),
        ('user', '0003_remove_userprofile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsetcompletedrecord',
            name='training_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.customtrainingset'),
        ),
    ]
