# Generated by Django 4.2.7 on 2023-11-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_trainingsetcompletedrecord_training_set'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trainingsetting',
            name='rest_time_range_check',
        ),
        migrations.AddConstraint(
            model_name='trainingsetting',
            constraint=models.CheckConstraint(check=models.Q(('rest_time__gt', 5), ('rest_time__lt', 120)), name='rest_time_range_check'),
        ),
    ]
