# Generated by Django 4.2.7 on 2023-11-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_trainingsetting_rest_time_range_check_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trainingsetting',
            name='rest_time_range_check',
        ),
        migrations.AddConstraint(
            model_name='trainingsetting',
            constraint=models.CheckConstraint(check=models.Q(('rest_time__gte', 5), ('rest_time__lte', 120)), name='rest_time_range_check'),
        ),
    ]
