# Generated by Django 4.2.7 on 2023-11-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_userprofile_height_in_cm_range_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height_in_cm',
            field=models.PositiveIntegerField(blank=True, default=170, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight_in_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=60.0, max_digits=5, null=True),
        ),
    ]
