# Generated by Django 4.2.7 on 2023-11-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_remove_customtrainingset_min_count_and_more'),
        ('user', '0009_userprofile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsetcompletedrecord',
            name='completed_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trainingsetcompletedrecord',
            name='training_set',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.customtrainingset'),
        ),
    ]
