# Generated by Django 4.2.7 on 2023-12-01 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_userprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsetting',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile'),
        ),
    ]
