# Generated by Django 4.2.7 on 2023-12-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_emailmessage_track_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='callback_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
