# Generated by Django 4.2.7 on 2023-12-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_emailmessage_callback_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='callback_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
