# Generated by Django 4.2.7 on 2023-11-25 15:44

from django.db import migrations
import enumfields.fields
import training.enums


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_rename_type_customtrainingset_training_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtrainingset',
            name='min_count',
        ),
        migrations.RemoveField(
            model_name='customtrainingset',
            name='valid_till',
        ),
        migrations.AddField(
            model_name='customtrainingset',
            name='level',
            field=enumfields.fields.EnumField(blank=True, default=None, enum=training.enums.TrainingLevel, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='customtrainingexercise',
            name='status',
            field=enumfields.fields.EnumField(default='ONG', enum=training.enums.TrainingStatus, max_length=3),
        ),
        migrations.AlterField(
            model_name='customtrainingset',
            name='status',
            field=enumfields.fields.EnumField(default='ONG', enum=training.enums.TrainingStatus, max_length=3),
        ),
    ]
