# Generated by Django 4.2.7 on 2023-12-03 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badges', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userachivementbadge',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.userprofile'),
        ),
        migrations.AddField(
            model_name='skeletonachivementbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='badges.badge'),
        ),
        migrations.AddField(
            model_name='skeletonachivementbadge',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='badges.track'),
        ),
    ]
