# Generated by Django 4.2.7 on 2023-12-03 08:59

import badges.enums
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='special_target',
            field=enumfields.fields.EnumField(enum=badges.enums.SpecialTargetType, help_text='[membership - to track about membership (user pay to upgrade to a non free tier) ( not appliable now )]  [streak - to track about a continuous action]  [weight - to track about user weight gain/loss]  ', max_length=3),
        ),
        migrations.AlterField(
            model_name='track',
            name='special_target_action',
            field=enumfields.fields.EnumField(enum=badges.enums.SpecialTargetAction, help_text='[paid - track the paid action (user pay to upgrade to a non free tier) ( not appliable now )]  [loss - user loss target weight successfully]  [gain - user gain target weight successfully]  ', max_length=3),
        ),
    ]
